#macro RIGHT 0
#macro UP 1
#macro LEFT 2
#macro DOWN 3
#macro RETURN 0
#macro NEW_ROOM 1
#macro LOAD 2
#macro MOVE 0
#macro IDLE 1
#macro ATTACK 2
#macro BRITNEY 0
#macro JO 1
#macro MIO 2
#macro ANNA 3
#macro SEBASTIAN 4
#macro GUNONE 0
#macro GUNTWO 1
#macro GRENADE 3
#macro MOUSE 0
#macro KEY 1
#macro ABILITY 0
#macro ULTIMATE 1
#macro DEAD 2
#macro NAME 3
